spring:
  application:
    name: index-codes-service
  redis:
    host: 139.199.225.229
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 1000000
    timeout: 50000
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
