feign:
  hystrix:
    enabled: true
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 1000000
    timeout: 50000
    database: 0
  application:
    name: index-gather-store-service
  zipkin:
    base-url: http://localhost:9411